HOST: http://api.cameraace.net/

--- CameraAce API ---

---
CameraAce API for supporting slideshow and group share.
---

--
Folder

The following is a section of resources related to the shared folder

    status
    --------------------------------------------------------------
    200         Success
    
API를 만들어주세요

--

Create a folder 
POST /v0/folder
> Content-Type: application/json
{ "name": "abcd",
  "desc": "abcd photo"
}
< 200
< Content-Type: application/json
{ "code": 0,
  "id": "sample-folder-id1"
}

Save new products in your shopping cart
POST /shopping-cart
> Content-Type: application/json
{ "product":"1AB23ORM", "quantity": 2 }
< 201
< Content-Type: application/json
{ "status": "created", "url": "/shopping-cart/2" }

ERROR CASE
POST /shopping-cart
> Content-Type: application/xml
< 200
< Content-Type: application/json
{"code": 1}

FOLDER UPDATE
GET /v0/folders/{folderId}
> Content-Type: application/json
< 200
< Content-Type: application/json
{}

FOLDER meeeep
POST /v0/folders/{folderId}
> Content-Type: application/json
< 200
< Content-Type: application/json
{}

--
Photo
--

photo_create

Create a photo, upload photo & thumbnail binary data.

Input =>

- mtype : mime-type
- psize : photo-byte-array-size
- tsize : thumbnail-byte-array-size
- pw : photo width
- ph : photo height
- tw : thumb width
- th : thumb height

Side Effects => 

- Create and associate a new PHOTO_RAW entry
- Add Photo to Folder’s photo_list
- Add this action to the Folder Log

POST /v0/folders/{folderId}/photos
> "sid": "ABCDEFG"
> Content-Type: application/json 
{ "mtype": "image/jpeg", 
   "psize" : 123456, 
   "tsize" : 12345, 
   "pw" : 1280, 
   "ph" : 960,  
   "tw" : 400,  
   "th" : 400  }
< 200
< Content-Type: application/json
{ "code":0, "description": "OK", "photoId": "ABCDEFG" }


photo_delete

Delete photo from folder.

Side Effects => 

- Remove the associated PHOTO_RAW entry
- Remove Photo from Folder’s photo_list
- Add this action to the Folder Log

DELETE /v0/folders/{folderId}/photos/{photoId}
> "sid": "ABCDEFG"
< 200
< Content-Type: application/json
{ "code":0, "description": “OK” }


photo_url

Get public url to download photo

GET /v0/folders/{folderId}/photos/{photoId}{?sid=ABCDEFG}
< 200
< Content-Type: application/json
{ "code":0, 
    "photoUrl": “http://some-url-to-download-photo”, 
    "thumbUrl" : “http://some-url-to-download-thumbnail” } 


